dist: xenial

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - pip install poetry
    - poetry install

script:
    - bash scripts/test.sh

after_script:
    - bash <(curl -s https://codecov.io/bash)

before_deploy:
    - poetry config pypi-token.pypi $PYPI_TOKEN

deploy:
    provider: script
    script: bash scripts/publish.sh
    on:
        tags: true
        python: "3.6"
